apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  type: NodePort 
  selector:
    app: deluge
  ports: 
  - name: http
    port: 8112
    targetPort: 8112
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222