apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
  name: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
      - env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: America/Denver
        - name: UMASK_SET
          value: '022'
        - name: DELUGE_LOGLEVEL
          value: info
        image: ghcr.io/linuxserver/deluge:latest
        imagePullPolicy: Always
        name: deluge
        volumeMounts:
        - name: deluge
          mountPath: /config
          subPath: deluge/config/
        - name: deluge
          mountPath: /downloads
          subPath: deluge/downloads  
      restartPolicy: Always
      volumes:
      - name: deluge
        persistentVolumeClaim:
          claimName: synology-deluge



