apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-deluge
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 500Gi